### PR TITLE
Problem: 17/C4 contains the incorrect editor

### PR DESCRIPTION
**Pull request by sjmackenzie**
Solution: remove stewart and replace with isaac

### CODE REVIEW

**Comment by whilei** [comment]
Oh, I see... I thought 'Editor' was like 'Chief Editor', like of a magazine.  👍

**Comment by sjmackenzie** [comment]
No no :-) I cannot endorse 17/C4, you are its champion I'm afraid. Basically this is how we handle disagreements in the community, or between different ethereum client implementations.

**Comment by sjmackenzie** [comment]
But please merge the PR!

**Comment by sjmackenzie** [comment]
Please read [2/COSS](https://etcrfc.that.world/spec:2/COSS) for more details about the Editor role.

**Comment by sjmackenzie** [comment]
So you as the lead of the go-ethereum project can choose to point to [17/C4](https://etcrfc.that.world/spec:17/C4)  and then it'll move from `raw` to `draft`. Once more projects in ETCDEV team use [17/C4](https://etcrfc.that.world/spec:17/C4)  then it'll become stable. But it would be far better if you actually used [1/C4](https://etcrfc.that.world/spec:1/C4) and got to deeply understand the process before you start making wild changes to a process that's been refined over years and adopted by many projects. my 2c worth.

**Pull request merged**
