### PR TITLE
Revert "Modify 2.3.7 git commit spec"

### PR DESCRIPTION
**Pull request by sjmackenzie**
Reverts ethereumproject/rfc#18

### CODE REVIEW

**Comment by sorpaas** [comment]
@whilei Can you create a new RFC, copy the current 1/C4 texts and append yours? 1/C4 is stable right now, which means it's actively being used. That's probably the rationale behind the revert.

@sjmackenzie Could you please provide some comments when reverting commits? Also, I suppose 1/C4 requires a different maintainer to merge the PR, correct?

**Comment by sjmackenzie** [comment]
Ah yes, that's correct 1/C4 is stable and can only accept cosmetic changes such as typos etc. This is the primary reason for the revert.

The secondary reason: the rationale of the Problem: ... Solution: ... is fundamental to the C4, it is an *empirical* process defined and evolved by a large group of programmers (not just ETC but many other communities that consist of very smart people). This is the actual change that introduces [2.3.7](https://github.com/hintjens/socialarchitecture/commit/198e32690e2d66d261277079f4a309fad058f548). The rationale is, if you can't explain the problem then you're writing code that doesn't solve a problem and thus the code is nonsense. You want your codebase to resemble a fighter jet with all fat trimmed. Too many programmers forget that others cannot mind read their understanding of the problem or even what the problem is. Writing what you did or where you did it is completely illogical, WHY is far more important. If you cannot justify why then remove the code. Using the argument that it's obvious and "upside down" also doesn't cut it, even those using the convention on a regluar basis slip up now and again, for example imagine you are a relative newbie and you read *just* the problem statement of this commit: https://github.com/ethereumproject/rfc/commit/904fcd41491927ed691c85e1ddf9728d2a3fe1f5, will you understand the problem? Now we have to understand what [sunglasses and a pen](https://github.com/ethereumproject/sputnikvm/commit/b4398d0f290466f8d818b44c13391ef3f47a4172) icon means? Hence the *explicit* *Problem: ... Solution: ...* forces the programmer to think ... "ah what was the problem... wait I have a few words to explain it briefly... let me think more clearly... hmm wait there are multiple problems here... darn it let me break this up into a few commits so only one problem per commit.... ahh okay this is it... I'm sure my readers will easily understand this... if not I'll try better next time..."

One problem per commit keeps the changes small and the maintainers can easily digest and merge the commit quickly instead of building *massive* PRs that introduce bugs and problems.

So it's not like writing a recipe book at all and naming it "I'm Hungry", though many commits are indeed simple problems i.e.
```
Problem: README formatting is verbose

Solution: tighten it up a little
```
 We're dealing with complex problems that need to be communicated to an audience of multiple technical levels, these problems could potentially have many solutions and describing *your* solution allows other people to see your deductive reasoning and "converse" *better* solutions with you via new PRs and not upfront consensus or chatting in PRs or long winded meetings.

Most importantly, we're not doing "enterprise coding" whereby we obscure the history and codebase such that we make ourselves the only one who understands the codebase and the problems history. We need to scan the problem history quickly and derive deductive reasoning for the changes as fast as possible.

**Comment by sjmackenzie** [comment]
@sorpaas "Also, I suppose 1/C4 requires a different maintainer to merge the PR, correct?" I saw the action as an atomic "revert" instead there were like three steps. This is basically the first time I've needed to revert. Also I was on my mobile. I'd have preferred making a new PR removing the change with its own message (and thus I wouldn't need to describe in the above comment). I'll make a new PR next time! (though in the case of troublesome vandals it's okay to just revert it)

**Comment by whilei** [comment]
@sorpaas Thanks, will do.

@sjmackenzie Aha, so I'm totally with you on your point about 1 problem, 1 solution per commit, with both being clearly stated in the commit. I'm also embarrassingly sure that I was not anywhere close to spec with the pen-eyeglasses; although I'm not sure [Improvements to C4, and cover](https://github.com/hintjens/socialarchitecture/commit/198e32690e2d66d261277079f4a309fad058f548) quite fit the bill either.

I think you missed my point about "upside-down"-edness and visual clarity/usability; my proposal deals very little content, and much more with visual display; why "Probem: " needs to go on top... (and why it must be fully stated; _eg_ "P:", used in this same context of spec'd commit messages, would serve the same purpose and be much less visually greedy).  

For example, when I read: 
```
Problem: README formatting is verbose
```
... I'm not sure what happened. Of course, I have my guesses, but I'm not sure. On a normal day I probably wouldn't track down that commit (being among others) to apply my deductive sport. However, some things that could've happened that I'll only discover when and if I click on the expand link or otherwise log verbosely:

```
Problem: README formatting is verbose

Solution: tightened the README syntax up a little
```

```
Problem: README formatting is verbose

Solution: include script to remove vowels from all words 
in README longer than 8 characters
```

```
Problem: README formatting is verbose

Solution: nuked the codebase and replaced README text with 'I am Ironman.'
```

__However__, if we instead suppose this last example's same formatting was "upside-down": 
```
Nuked the codebase and replaced README text with 'I am Ironman.'
```
 then we'd be able to kickoff some hearty log expansion and interrogation before we even finish sitting down.

Which leads me to ask about your comment; 
> We need to scan the problem history quickly and derive deductive reasoning for the changes as fast as possible.

Why is it more important to you to scan the _problem history_ than the _solve history_?  Or is it?

**Comment by sjmackenzie** [comment]
@whilei I'll address your issues one at a time.

> I'm not sure [Improvements to C4, and cover](https://github.com/hintjens/socialarchitecture/commit/198e32690e2d66d261277079f4a309fad058f548) quite fit the bill either. 

Understood, this is an empirical process, when we first degassed a vacuum gauge under vacuum it completely messed up our vacuum. It took time to develop the habit and muscle memory to degas properly. Even now we discovered a problem that gave us incorrect readings. 

> For example, when I read:
```
Problem: README formatting is verbose
```
> ... I'm not sure what happened.

You know if that problem is interesting enough to drill into, next level is "ah what did the guy do?" click expand and see the solution. Or if the problem is close to what you're dealing with or have dealt with you click the link and see the actual patch. The patch is the 3 rd stage. A commit message that describes nothing forces the person skimming over the problems to go into each diff which is complexity overload.

Anyway

> Why is it more important to you to scan the problem history than the solve history? Or is it?

Cause I want to see what the problems are, the problem is the cause for movement. If I'm interested in how you solved it then I'll drill in. After all... there are an infinite set of solutions, knowing problems to solve makes most efficient use of your time.

**Comment by sjmackenzie** [comment]
regarding why not use 

```
P: ...
```
Imagine you are an experienced developer and you have been writing commit messages that only contain the text ":eyeglasses: :pen:" all your working career. Now you come across a project that has a commit message 
```
P: firmware PID parameters are incorrect

S: adjust the derivative 
```
What will you think?
What does P mean? what does S mean?

Now let's read it again:
```
Problem: firmware PID parameters are incorrect

Solution: adjust the derivative
```
It makes a big difference to your new readers. To you it feels like verbose repetitiveness but actually it's important for your reader. 1/C4 is about making change into the repository seamless as possible.

**Comment by whilei** [comment]
Hahaa... let it forever be known as _The Infamous Pen-Eyeglasses Commit of 2017_. 

In general I read ya loud and clear. Just adjusting to the format is a little awkward for me; I don't plan to point go-ethereum to 17/4C anytime soon without further support from the team/community. It's also nice to finally get a feel for how this RFC project is structured and processes -- I :heart:.

And another benefit of the `stable` way is w/r/t
> After all... there are an infinite set of solutions, knowing problems to solve makes most efficient use of your time.

can also be effective for tracking the same problem temporally, which I hadn't put much thought into, _ie_

```
Problem: accounts module indexing hangs
<Solution: remove mutex lock from cache find method>
---
Problem: accounts module indexing hangs
<Solution: unremove mutex lock and instead ensure watcher is started>
```

which is a visually effective way of signaling an ongoing issue and providing related solve-attempts for the interested.

**Comment by sjmackenzie** [comment]
```
Problem: accounts module indexing hangs
<Solution: remove mutex lock from cache find method>
---
Problem: accounts module indexing hangs
<Solution: unremove mutex lock and instead ensure watcher is started>
```
now that shit rocks.... I've been struggling with this for a while. I'll think about this! Thanks!

**Pull request merged**
